source "https://rubygems.org"

gem "rails", "~> 8.1.1"
gem "pg", "~> 1.6"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "kamal", require: false
gem "thruster", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

# HTTP 客户端，用于调用后端 API
gem "httparty"

# JSON 序列化
gem "jsonapi-serializer"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
