source "https://rubygems.org"

gem "rails", "~> 8.1.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "sidekiq"
gem "redis", ">= 4.0"
gem "kamal", require: false
gem "thruster", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

# HTTP 客户端，用于调用后端 API
gem "httparty"

# JSON 序列化
gem "jsonapi-serializer"

# Phlex - 纯 Ruby HTML 组件，零模板
gem "phlex", "~> 2.0"
gem "phlex-rails", "~> 2.0"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
