default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: minechat_development

test:
  <<: *default
  database: minechat_test

production:
  <<: *default
  url: <%= ENV["MINECHAT_DATABASE_URL"] %>
