# Ruboto Android 项目 Rakefile
require "rexml/document"
require "ruboto"

PROJECT_DIR = File.expand_path(".")

# 加载 Ruboto 内置的 Rake 任务
load File.join(Ruboto::GEM_ROOT, "assets", "rakelib", "ruboto.rake")

# 项目配置写入 ruboto.yml
RUBOTO_YML = File.join(PROJECT_DIR, "ruboto.yml")

unless File.exist?(RUBOTO_YML)
  File.write(RUBOTO_YML, YAML.dump({
    "name" => "Minechat",
    "package_name" => "com.minechat.app",
    "min_sdk" => 21,
    "target_sdk" => 34,
    "version_code" => 1,
    "version_name" => "1.0.0",
    "api_url" => ENV.fetch("MINECHAT_API_URL", "http://10.0.2.2:3000"),
  }))
end
