name: CI (Backend)

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml'

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: backend

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager
        working-directory: backend

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: backend

      - name: Lint code for consistent style
        run: bin/rubocop -f github
        working-directory: backend

  test:
    runs-on: ubuntu-latest

    # IBM DB2 服务
    services:
      db2:
        image: icr.io/db2_community/db2
        env:
          LICENSE: accept
          DB2INSTANCE: db2inst1
          DB2INST1_PASSWORD: db2inst1-pwd
          DBNAME: MINECHAT
          CREATE_DB: true
        ports:
          - 50000:50000
        options: --privileged=true --health-cmd="su - db2inst1 -c 'db2 connect to MINECHAT'" --health-interval=10s --health-timeout=10s --health-retries=20

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: backend

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: ibm-db://db2inst1:db2inst1-pwd@localhost:50000/MINECHAT_TEST
          SCHEMA: DB2INST1
        run: bin/rails db:test:prepare test
        working-directory: backend
